# Generated by Django 4.2.4 on 2023-10-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verif_email_code',
            field=models.IntegerField(default=0, verbose_name='код верификации почты'),
        ),
    ]
