# Generated by Django 4.2.4 on 2023-10-21 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_verif_email_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата регистрации'),
        ),
    ]
