# Generated by Django 4.2.4 on 2023-10-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_date_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_create',
            new_name='created_at',
        ),
    ]
