# Generated by Django 4.2.4 on 2023-10-08 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='data_crate',
        ),
        migrations.AddField(
            model_name='blog',
            name='publ_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата создания'),
        ),
    ]
