# Generated by Django 4.2.4 on 2023-10-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_data_crate_blog_publ_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='превью'),
        ),
    ]
