# Generated by Django 4.2.4 on 2023-10-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publ_sign',
            new_name='is_valid',
        ),
    ]
