# Generated by Django 4.2.4 on 2023-11-15 06:40

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_interval', django.contrib.postgres.fields.ranges.DateRangeField(verbose_name='дата начала и окончания')),
                ('send_time', models.TimeField()),
                ('periodicity', models.PositiveIntegerField(choices=[(1, 'раз в день'), (7, 'раз в неделю'), (30, 'раз в месяц'), (2, 'другое')])),
                ('custom_periodicity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('finished', 'Завершена')], default='created', max_length=10)),
            ],
        ),
    ]
