# Generated by Django 4.2.4 on 2023-11-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='periodicity',
            field=models.PositiveIntegerField(choices=[(0, 'один раз'), (1, 'раз в день'), (7, 'раз в неделю'), (30, 'раз в месяц'), (2, 'другое')]),
        ),
    ]
