# Generated by Django 4.2.4 on 2023-11-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft_1', '0003_alter_settings_date_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='custom_periodicity',
        ),
    ]
