# Generated by Django 4.2.4 on 2023-09-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_change',
            field=models.DateTimeField(null=True, verbose_name='дата последнего изменения'),
        ),
    ]
