# Generated by Django 4.2.4 on 2023-10-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_version', models.IntegerField(verbose_name='номер версии')),
                ('name_version', models.CharField(max_length=50, verbose_name='имя версии')),
                ('is_active', models.BooleanField(default=True, verbose_name='активация')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
                'ordering': ('name_version',),
            },
        ),
    ]
