# Generated by Django 4.2.4 on 2023-10-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
